### ISSUE TITLE
使用npm不使用本地的dva-core 文件会报错

### ISSUE THREAD

**Issue by Nodewebzsz** [shenqihui/taro_scaffold#2]
`VM4987:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/core-js/library/fn/object/get-own-property-descriptor.js" is not defined 
 Error: module "npm/core-js/library/fn/object/get-own-property-descriptor.js" is not defined
    at require (http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:20138)
    at http://127.0.0.1:44596/appservice/__dev__/WAService.js:22:19993
    at http://127.0.0.1:44596/appservice/npm/@babel/runtime/core-js/object/get-own-property-descriptor.js:1:328`

**Comment by shenqihui** [comment]
对的。所以需要单独迁出一个出来，进行轻微的改造。

等什么时候 Taro 支持编译 node_modules 时候才能使用 npm 包版本的 dva-core

**Comment by Nodewebzsz** [comment]
那就尴尬了
