### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zcSkr** [shenqihui/taro_scaffold#6]
![image](https://user-images.githubusercontent.com/30515821/49977854-e5bcff00-ff82-11e8-8b65-094b702f6eda.png)

**Comment by shenqihui** [comment]
@zcSkr 可能版本跟不上了。贴下你的关键的 taro 版本。我晚点看看。

**Comment by shenqihui** [comment]
更新到最新的，也未出现此情况。

**Comment by shenqihui** [comment]
应该是taro相关的bug了。

**Comment by shenqihui** [comment]
closed
